# Generated by Django 2.0 on 2020-07-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('location', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProxyPerson',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('ProxyApp.person',),
        ),
    ]
