# Generated by Django 3.0 on 2020-07-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50)),
                ('course_price', models.IntegerField()),
                ('course_description', models.CharField(max_length=200)),
                ('course_requirment', models.CharField(max_length=200)),
                ('url_link', models.URLField(max_length=500)),
                ('status_choices', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=50)),
                ('course_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculam1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headings', models.CharField(max_length=500)),
                ('AddCourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuizeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quize_title', models.CharField(max_length=100)),
                ('CourseQuizeTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('type_of_ans', models.CharField(choices=[('Single_Answer', 'SINGLE'), ('Multi_Answer', 'MULTI'), ('Dragula_Answer', 'DRAGULA')], default='Single_Answer', max_length=50)),
                ('AddQuizeTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.QuizeTitle')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCurriculam2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headings', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='')),
                ('AddCourseCurriculam1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.CourseCurriculam1')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(to='ELearningApp.Tag'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_no', models.IntegerField()),
                ('ans', models.TextField(max_length=500)),
                ('wrong_or_right', models.CharField(choices=[('wrong', 'wrong'), ('right', 'right')], default='wrong', max_length=100)),
                ('AddQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ELearningApp.Questions')),
            ],
        ),
    ]
